'use strict';
const E=NaturalEngine, $=s=>document.querySelector(s), esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const state={name:'',start:null,page:'inici',level:'mitja',games:{},rounds:[],attempts:[],time:{},hints:{},clock:Date.now(),finished:null,exported:0};
const recent=new Set();
const def=id=>E.definitions.find(d=>d.id===id), current=()=>state.games[state.page];
const date=d=>new Intl.DateTimeFormat('ca-ES',{dateStyle:'long',timeStyle:'short',timeZone:'Europe/Madrid'}).format(d);
const duration=ms=>`${Math.floor(ms/60000)} min ${Math.floor(ms/1000)%60} s`;
const main=$('#main');
function tick(){const now=Date.now();if(state.name&&!document.hidden&&def(state.page)&&!state.finished)state.time[state.page]=(state.time[state.page]||0)+Math.min(now-state.clock,5000);state.clock=now;}
setInterval(tick,1000);document.addEventListener('visibilitychange',()=>{tick();state.clock=Date.now();});
const islandLabels=['La platja','La palmera','El pont','La cova','El volcà','El cofre'];
const isPassed=r=>r.done&&r.passed!==false&&!r.abandoned;
const solvedCount=r=>r.id==='tresor'?r.outcomes.filter(x=>x==='assolit').length:r.index+(r.pending?1:0)-(r.failedQuestions?.length||0);
const roundStatus=r=>isPassed(r)?'Superada':r.abandoned?'No superada (deixada a mitges)':r.done?'No superada (proves no assolides)':'No superada (en curs)';
function islandMap(r){
 const points=[[184,359],[213,152],[431,139],[550,260],[711,178],[758,408]];
 return `<figure class="treasure-map"><img src="assets/comic/illa-mapa.webp?v=5" alt="Illa amb una platja, una palmera, un pont, una cova, un volcà i un cofre"><svg class="map-status" viewBox="0 0 900 570" aria-hidden="true">${points.map(([x,y],i)=>{const status=r.outcomes[i],color=status==='assolit'?'#176c40':status==='fallat'?'#b32726':'#111127';return `<g class="landmark ${status}" transform="translate(${x} ${y})">${i===r.index&&!r.done&&status==='pendent'?'<ellipse rx="65" ry="65" fill="none" stroke="#ffe365" stroke-width="8"/>':''}${status==='assolit'?'<path d="M-45 -45L45 45M-45 45L45 -45" stroke="#176c40" stroke-width="8" stroke-linecap="round"/>':status==='fallat'?'<circle r="57" fill="#ff5b5420" stroke="#b32726" stroke-width="7"/><path d="M-25 -25L25 25M-25 25L25 -25" stroke="#b32726" stroke-width="8"/>':''}<rect x="-75" y="67" width="150" height="31" rx="5" fill="${status==='assolit'?'#b9f4d1':status==='fallat'?'#ffd5cf':'#fff5dc'}" stroke="${color}" stroke-width="3"/><text y="89" text-anchor="middle" fill="${color}" font-family="Arial,sans-serif" font-size="20" font-weight="bold" ${status==='assolit'?'text-decoration="line-through"':''}>${i+1}. ${islandLabels[i]}</text></g>`;}).join('')}</svg><figcaption><span>Groc: prova actual</span><span>Verd: assolit i tatxat</span><span>Vermell: no assolit</span></figcaption></figure><ul class="island-checklist">${islandLabels.map((l,i)=>`<li class="${r.outcomes[i]}">${r.outcomes[i]==='assolit'?'✓':r.outcomes[i]==='fallat'?'✕':'○'} ${l}: ${r.outcomes[i]==='assolit'?'assolit':r.outcomes[i]==='fallat'?'no assolit':'pendent'}</li>`).join('')}</ul>`;
}
function statistics(id){const a=state.attempts.filter(x=>!id||x.id===id),rounds=state.rounds.filter(r=>!id||r.id===id);return {ok:a.filter(x=>x.ok).length,bad:a.filter(x=>!x.ok).length,corrected:a.filter(x=>x.ok&&x.corrected).length,rounds:rounds.length,completed:rounds.filter(isPassed).length,incomplete:rounds.filter(x=>!x.done).length,failed:rounds.filter(x=>x.done&&!isPassed(x)).length,notPassed:rounds.filter(x=>!isPassed(x)).length,hints:id?(state.hints[id]||0):Object.values(state.hints).reduce((a,b)=>a+b,0),time:id?(state.time[id]||0):Object.values(state.time).reduce((a,b)=>a+b,0)};}
function bar(id){let s=statistics(id),total=s.ok+s.bad;return `<div class="bar" role="img" aria-label="${s.ok} encerts i ${s.bad} errades"><span class="ok" style="width:${total?s.ok/total*100:0}%"></span><span class="bad" style="width:${total?s.bad/total*100:0}%"></span></div><div class="legend"><span class="ok">● ${s.ok} encerts</span><span class="bad">● ${s.bad} errades</span><span>${total?Math.round(s.ok/total*100)+'% d’encerts':'Sense respostes'}</span></div>`;}
function record(r,text,answer,expected,ok){let prior=state.attempts.some(a=>a.round===r.serial&&a.index===r.index&&!a.ok);state.attempts.push({id:r.id,round:r.serial,index:r.index,level:r.level,text,answer:String(answer),expected:String(expected),ok,corrected:ok&&prior,hint:r.hintShown,at:Date.now()});r.touched=true;}
function feedback(r,text,type='neutral'){r.feedback=text;r.feedbackType=type;}
function feedbackHTML(r){return `<div class="feedback ${r.feedbackType==='wrong'?'wrong':r.feedbackType==='neutral'?'neutral':''}" role="status">${esc(r.feedback)}</div>`;}
function newGame(id){const old=state.games[id];if(old&&!old.done&&old.touched&&!confirm('La partida actual quedarà no superada (deixada a mitges) a l’informe. Vols començar una partida nova?'))return;if(old&&!old.done)old.abandoned=true;let r,signature;for(let i=0;i<50;i++){r=E.create(id,state.level);signature=JSON.stringify(r.questions||r.tiles);if(!recent.has(signature))break;}recent.add(signature);r.failedQuestions=[];r.failedCells=[];r.hintFailures=0;r.serial=state.rounds.length+1;state.games[id]=r;state.rounds.push(r);render();}
function nav(){ $('#nav').innerHTML=`<button data-nav="inici" class="${state.page==='inici'?'active':''}" ${state.page==='inici'?'aria-current="page"':''}>⌂ Inici</button>`+E.definitions.map(d=>`<button data-nav="${d.id}" class="${state.page===d.id?'active':''}" ${state.page===d.id?'aria-current="page"':''}><img src="assets/comic/${d.id}.webp?v=5" alt="">${d.name}</button>`).join('')+`<button data-nav="progres" class="${state.page==='progres'?'active':''}" ${state.page==='progres'?'aria-current="page"':''}>▥ El meu progrés</button><a class="escape" href="https://jjbavatares.github.io/missio-orio/" target="_blank" rel="noopener noreferrer" aria-label="Missió Orió, s’obre en una pestanya nova">Missió Orió ↗</a>`;
  $('#session-bar').innerHTML=state.name?`<span><strong>${esc(state.name)}</strong> · Sessió iniciada: ${date(state.start)}</span><span>Les dades no es guarden. Descarrega el PDF abans de sortir.</span>`:`<span>Una sessió, vuit maneres de practicar.</span><span>Sense comptes · Sense dades desades</span>`;
}
function navigate(id){tick();state.page=id;if(state.name&&def(id)&&!state.games[id])newGame(id);else render();if(location.hash!==`#${id}`)history.replaceState(null,'',`#${id}`);main.focus({preventScroll:true});}
function home(){return `<section class="hero"><div><p class="eyebrow">Matemàtiques · 1r d’ESO</p><h1>EL CLUB<span>DELS NOMBRES NATURALS</span></h1><p>Compra, investiga, construeix i juga. Vuit activitats per posar a prova els nombres naturals, al teu ritme.</p><div class="facts"><div><strong>8</strong><span>mons per explorar</span></div><div><strong>∞</strong><span>noves partides</span></div><div><strong>1 PDF</strong><span>el treball de la sessió</span></div></div></div><div class="hero-art"><img src="assets/comic/portada.webp?v=5" alt="Il·lustració de còmic amb una illa del tresor, un mercat, fitxes, una lupa i un corredor"></div></section><div class="notice"><strong>Important: el progrés no es guarda.</strong> En tancar o recarregar aquesta pàgina, es perden el nom i tots els resultats. A «El meu progrés» pots descarregar un PDF per enviar-lo al professor o professora.</div>${state.name?`<div class="panel"><h2>Benvingut/uda, ${esc(state.name)}!</h2><p>Tria una activitat. Pots canviar de pestanya i tornar-hi sense perdre la partida, mentre aquesta pàgina continuï oberta.</p><button class="button" data-nav="progres">Consulta el meu progrés</button></div>`:`<form class="panel name-form" id="name-form"><div><label for="student-name">Nom complet de l’alumne/a</label><input id="student-name" name="name" autocomplete="off" maxlength="80" required placeholder="Nom i cognoms"><p style="font-size:.85rem;margin:8px 0 0">Apareixerà a l’informe. No s’envia a cap servidor.</p></div><button class="button" type="submit">Comença la sessió</button></form>`}<section class="cards" aria-label="Tria una activitat">${E.definitions.map(d=>`<article class="card"><img src="assets/comic/${d.id}.webp?v=5" alt="${esc(d.title)}"><h3>${d.name}</h3><p>${d.desc}</p><button class="button cyan" data-nav="${d.id}">Entra al joc →</button></article>`).join('')}</section>`;}
function locked(){return `<div class="panel"><h2>Primer, identifica’t</h2><p>Escriu el nom complet a la pàgina inicial per començar una sessió i poder generar l’informe.</p><button class="button" data-nav="inici">Ves a l’inici</button></div>`;}
function completed(r){const passed=isPassed(r),total=r.id==='domino'?6:r.questions.length;return `${r.id==='tresor'?islandMap(r):''}<div class="round-complete ${passed?'':'not-passed'}">${passed?'<img class="trophy" src="assets/comic/trofeu.webp?v=5" alt="Trofeu de partida superada">':''}<h2>${!passed?(r.id==='tresor'?'Expedició no superada':'Partida no superada'):r.id==='bingo'?'BINGO!':r.id==='tresor'?'Tresor descobert!':r.id==='cursa'?'Has arribat a la meta!':'Partida superada!'}</h2><p>${passed?'Has superat tots els reptes. Els intents i les correccions ja apareixen al teu informe.':`Has assolit ${solvedCount(r)} de ${total} reptes. Les proves no assolides consten com a errors a l’informe. Pots provar una altra partida amb dades noves.`}</p><div class="actions" style="justify-content:center"><button class="button" data-new>Una altra partida</button><button class="small" data-nav="progres">Veure el progrés</button></div></div>`;}

function answerForm(r,question){return `<form class="entry" id="answer-form"><div><label for="answer">La teva resposta (nombre natural)</label><input id="answer" name="answer" inputmode="numeric" autocomplete="off" required pattern="[0-9]+" placeholder="Escriu el nombre sense punts"></div><button class="button" type="submit">Comprova</button></form>`;}
function hintHTML(r,q){return `<div class="actions"><button class="small" data-hint ${r.hintShown?'disabled':''}>${r.hintShown?'Pista utilitzada':'Necessito una pista'}</button></div>${r.hintShown?`<div class="hint">${esc(q.hint||'Calcula cada preu multiplicat per la quantitat, suma els imports i resta el total dels diners entregats.')}<p class="hint-attempts">${r.pending?'Prova finalitzada.':`Intents disponibles després de la pista: ${2-(r.hintFailures||0)} de 2.`}</p></div>`:''}`;}

function gameplay(r){const q=r.questions?.[r.index];if(r.done)return completed(r);
 if(r.id==='bingo')return `<p class="eyebrow" style="color:#007a9e">Pista ${r.index+1} de 9</p><div class="question bingo-question ${!r.pending&&r.index>0?'new-operation':''}" aria-live="polite">${!r.pending&&r.index>0?'<span class="new-operation-label">NOVA OPERACIÓ</span>':''}Quin nombre és el resultat de ${esc(q.text)}?</div><div class="bingo-grid">${r.cells.map(n=>`<button class="bingo-cell ${r.marked.includes(n)?'marked':r.failedCells.includes(n)?'failed':''}" data-cell="${n}" ${r.marked.includes(n)||r.failedCells.includes(n)?'disabled':''} aria-label="${n}${r.marked.includes(n)?', ja marcat':r.failedCells.includes(n)?', prova no assolida':''}">${E.fmt(n)}</button>`).join('')}</div>${feedbackHTML(r)}${hintHTML(r,q)}`;
 if(r.id==='mercat')return `<p class="eyebrow" style="color:#007a9e">Compra ${r.index+1} de 5</p><div class="product-grid">${q.products.map(p=>`<div class="product"><img src="assets/comic/${p.icon}.webp?v=5" alt="${p.name}"><strong>${p.name}</strong><span class="price">${p.price} €</span><p style="margin:5px 0 0">${p.qty} ${p.qty===1?'unitat':'unitats'}</p></div>`).join('')}</div><div class="question">Compres les quantitats indicades i pagues amb ${q.paid} €. Quin és el total i quant canvi reps?</div><form class="entry" id="market-form"><div><label for="total">Total de la compra (€)</label><input id="total" name="total" inputmode="numeric" pattern="[0-9]+" required autocomplete="off"></div><div><label for="change">Canvi (€)</label><input id="change" name="change" inputmode="numeric" pattern="[0-9]+" required autocomplete="off"></div><button class="button" type="submit">Comprova</button></form>${feedbackHTML(r)}${hintHTML(r,q)}`;
 if(r.id==='domino')return `<p>Arrossega una fitxa a la zona blava. Amb teclat o pantalla tàctil, selecciona la fitxa i després prem la zona.</p><div class="question">Extrem de la cadena: ${esc(r.chain.length?r.chain.at(-1).operation:r.start)}</div><div class="chain">${r.chain.map(t=>`<span class="${t.revealed?'revealed':''}" ${t.revealed?'title="Fitxa mostrada com a solució; prova no assolida"':''}>${t.left} │ ${t.operation}${t.revealed?' · Solució':''}</span>`).join('')}</div><button class="drop-zone" id="domino-drop"><strong>Col·loca aquí la fitxa següent</strong>La xifra de l’esquerra ha de coincidir amb el resultat.</button><div class="domino-tray">${r.tiles.filter(t=>!r.chain.some(c=>c.key===t.key)).map(t=>`<button class="domino ${r.selected===t.key?'selected':''}" draggable="true" data-tile="${t.key}" aria-pressed="${r.selected===t.key}"><span>${t.left}</span><span>${t.operation}</span></button>`).join('')}</div>${feedbackHTML(r)}${hintHTML(r,{hint:'Calcula l’operació de l’extrem. Busca aquest resultat a l’esquerra d’una fitxa.'})}`;
 if(r.id==='tresor')return `${islandMap(r)}<p class="eyebrow" style="color:#007a9e">Prova ${r.index+1} de 6 · ${islandLabels[r.index]}</p><p class="attempts-left">${r.pending?(r.outcomes[r.index]==='assolit'?'Prova assolida':'Prova no assolida'):`Intents disponibles: ${2-r.failures[r.index]} de 2`}</p><div class="question">${esc(q.text)}</div>${answerForm(r,q)}${feedbackHTML(r)}${hintHTML(r,q)}`;
 if(r.id==='cursa')return `<div class="track" aria-label="Casella ${r.index+1} de 8">${Array.from({length:8},(_,i)=>`<div class="${r.failedQuestions.includes(i)?'failed':i<r.index?'done':''}">${i===r.index?'<img class="runner" src="assets/comic/corredor.webp?v=5" alt="El teu corredor">':r.failedQuestions.includes(i)?'✕':i<r.index?'✓':i===7?'⚑':i+1}</div>`).join('')}</div><p class="eyebrow" style="color:#007a9e">Repte ${r.index+1} de 8</p><div class="question">${esc(q.text)}</div>${answerForm(r,q)}${feedbackHTML(r)}${hintHTML(r,q)}`;
 if(r.id==='misteri')return `<p class="eyebrow" style="color:#007a9e">Investigació ${r.index+1} de 5</p><div class="question">Quin nombre de quatre xifres s’amaga al laboratori?</div><div class="clues">${q.clues.map((c,i)=>`<div class="clue"><strong>PISTA ${i+1}</strong>${esc(c)}</div>`).join('')}</div>${answerForm(r,q)}${feedbackHTML(r)}${hintHTML(r,q)}`;
 if(r.id==='construccio')return `<p class="eyebrow" style="color:#007a9e">Construcció ${r.index+1} de 5</p><div class="question">${q.text}</div><p>Arrossega les xifres. També pots seleccionar una xifra i prémer una casella buida. Prem una casella ocupada per tornar la xifra al taller.</p><div class="digit-tray">${q.digits.map((d,i)=>!q.slots.includes(i)?`<button class="digit ${r.selected===i?'selected':''}" draggable="true" data-digit="${i}" aria-pressed="${r.selected===i}" aria-label="Xifra ${d}">${d}</button>`:'').join('')}</div><div class="digit-slots">${q.slots.map((v,i)=>`<button class="digit-slot ${v!==null?'filled':''}" data-slot="${i}" aria-label="Posició ${i+1}${v===null?', buida':', xifra '+q.digits[v]}">${v===null?'?':q.digits[v]}</button>`).join('')}</div><button class="button" data-check-build>Comprova el nombre</button>${feedbackHTML(r)}${hintHTML(r,q)}`;
 if(r.id==='detectius')return `<p class="eyebrow" style="color:#007a9e">Cas ${r.index+1} de 5</p><div class="question">Troba el primer pas incorrecte.</div><div class="error-lines">${q.lines.map((l,i)=>`<button class="error-line ${r.selected===i?'selected':''}" data-line="${i}" aria-pressed="${r.selected===i}"><b>${i+1}</b>${esc(l)}</button>`).join('')}</div><form class="entry" id="detective-form"><div><label for="answer">Resultat correcte de tota l’operació</label><input id="answer" name="answer" inputmode="numeric" pattern="[0-9]+" required autocomplete="off"></div><button class="button" type="submit">Resol el cas</button></form>${feedbackHTML(r)}${hintHTML(r,q)}`;
}
function activity(id){let d=def(id);if(!state.name)return locked();const r=current(),s=statistics(id);return `<header class="activity-title"><div><p class="eyebrow">${d.topic}</p><h1>${d.title}</h1></div><div class="tools"><div><label for="level">Nivell de la pròxima partida</label><select id="level"><option value="inicial" ${state.level==='inicial'?'selected':''}>Inicial</option><option value="mitja" ${state.level==='mitja'?'selected':''}>Mitjà</option><option value="repte" ${state.level==='repte'?'selected':''}>Repte</option></select></div><button class="button cyan" data-new>Nova partida</button></div></header><div class="game-layout"><aside><div class="game-branding"><img src="assets/jjb-avatares.webp?v=4" alt="JJB Avatares con IA"></div><div class="scene"><img src="assets/comic/${id}.webp?v=5" alt="${d.title}"><div class="scene-caption"><h3>Com es juga?</h3><p>${d.instructions}</p></div></div><div class="score-strip"><span><strong>${s.ok}</strong> encerts</span><span><strong>${s.bad}</strong> errades</span><span><strong>${s.hints}</strong> pistes</span><span>Nivell: <strong>${r.level==='mitja'?'mitjà':r.level}</strong></span></div><p class="muted" style="font-size:.85rem">${id==='tresor'?'Tens dos intents per indret. Per superar l’expedició cal assolir-los tots.':'Després de consultar la pista tens dos intents. Si fallen, veuràs la solució i podràs continuar.'} Cada intent queda registrat. Una partida deixada a mitges no està superada.</p></aside><section class="panel" aria-label="Tauler del joc">${gameplay(r)}</section></div>`;}
function progress(){if(!state.name)return locked();const s=statistics();return `<div class="report-top"><div><p class="eyebrow">Informe de la sessió actual</p><h1>El meu progrés</h1><p><strong>${esc(state.name)}</strong><br>${date(state.start)}<br>Temps actiu en activitats: ${duration(s.time)}</p></div><div><button class="button" data-pdf>Descarrega l’informe en PDF</button><p style="margin-top:12px;font-size:.85rem">Per adjuntar-lo al correu o a Classroom.</p></div></div><div class="notice">El PDF recull el resum de la sessió en una sola pàgina. Aquí també pots consultar el detall dels intents. <strong>No es guarda en tancar o recarregar.</strong> Missió Orió s’obre en una altra web i els seus resultats no s’inclouen aquí.</div><div class="report-card"><h3>Resum de la sessió</h3>${bar()}<div class="stats"><span>${s.rounds} partides iniciades</span><span>${s.completed} superades</span><span>${s.notPassed} no superades</span><span>${s.corrected} reptes corregits després d’un error</span><span>${s.hints} pistes</span></div></div><div class="report-cards" style="margin-top:20px">${E.definitions.map(d=>{let t=statistics(d.id);return `<article class="report-card"><h3>${d.name}</h3><p style="font-size:.85rem;margin:0">${d.topic}</p>${bar(d.id)}<div class="stats"><span>${t.completed}/${t.rounds} partides superades</span><span>${t.notPassed} no superades</span><span>${t.corrected} correccions</span><span>${t.hints} pistes</span><span>${duration(t.time)}</span></div>${t.bad?'<p style="margin:15px 0 0;font-size:.85rem">Per repassar: '+d.topic.toLowerCase()+'.</p>':''}</article>`;}).join('')}</div><p class="muted" style="margin-top:20px;font-size:.85rem">Un intent és una comprovació enviada. Al mercat compta la compra completa; als detectius, el pas i el resultat junts. Els encerts després d’un error també es compten i s’indiquen com a correccions. El temps només compta amb l’activitat oberta i visible.</p><details open><summary>Estat de les partides</summary><div class="table-wrap"><table><thead><tr><th>Activitat</th><th>Partida</th><th>Estat</th><th>Reptes assolits</th></tr></thead><tbody>${state.rounds.map(r=>`<tr><td>${def(r.id).name}</td><td>${r.serial} · ${r.level}</td><td>${roundStatus(r)}</td><td>${solvedCount(r)} / ${r.id==='domino'?6:r.questions.length}</td></tr>`).join('')||'<tr><td colspan="4">Encara no hi ha partides.</td></tr>'}</tbody></table></div></details><details><summary>Veure el detall dels ${state.attempts.length} intents</summary><div class="table-wrap"><table><thead><tr><th>Activitat</th><th>Repte</th><th>Resposta</th><th>Resultat</th></tr></thead><tbody>${state.attempts.map(a=>`<tr><td>${def(a.id).name}<br>Partida ${a.round} · ${a.level}</td><td>${esc(a.text)}</td><td>${esc(a.answer)}</td><td>${a.ok?'Encert':'Error'}${a.corrected?' · Corregit':''}${a.hint?' · Amb pista':''}</td></tr>`).join('')||'<tr><td colspan="4">Encara no hi ha intents.</td></tr>'}</tbody></table></div></details>`;}
function render(){nav();document.querySelector('footer img').hidden=!!def(state.page);main.innerHTML=state.page==='inici'?home():state.page==='progres'?progress():activity(state.page);const r=current();if(r?.pending){const zone=main.querySelector('.panel[aria-label]');if(zone){zone.querySelectorAll('button,input,select').forEach(b=>{b.disabled=true;b.draggable=false;});const last=r.index===(r.id==='domino'?5:r.questions.length-1);zone.insertAdjacentHTML('beforeend',`<div class="actions next-action"><button class="button cyan" data-next>${last?'Veure el resultat':r.id==='bingo'?'Operació següent':'Repte següent'} →</button></div>`);}}}

function advance(r){if(r.id==='domino'){const tile=r.tiles.find(t=>t.left===r.expected);r.chain.push({...tile,revealed:true});r.expected=tile.next;}r.index++;r.hintShown=false;r.hintFailures=0;r.selected=null;r.feedback='';if(r.index>=(r.id==='domino'?6:r.questions.length)){r.done=true;if(r.id==='tresor')r.passed=r.outcomes.every(x=>x==='assolit');}render();const target=main.querySelector('.bingo-question,.question,.round-complete');target?.scrollIntoView({behavior:'smooth',block:'nearest'});}

function success(r){feedback(r,r.id==='bingo'?'Casella correcta! Prem «Operació següent» per veure una nova operació.':'Correcte! Aquesta prova ja està assolida. Prem el botó següent per continuar.','ok');if(r.id==='tresor'){r.outcomes[r.index]='assolit';r.pending=true;}else if(r.id==='bingo'){if(r.index===8){r.index++;r.done=true;}else r.pending=true;}else if(r.index===r.questions.length-1){r.index++;r.done=true;r.pending=false;}else r.pending=true;render();}

function numeric(value){return /^\d+$/.test(String(value))&&Number.isSafeInteger(Number(value));}
function tryAnswer(answer,extra){const r=current();if(!r||r.done||r.pending)return;const q=r.questions[r.index];let ok,text=q.text||'Nombre misteriós',expected=q.answer,submitted=answer;
 if(r.id==='mercat'){ok=Number(answer)===q.total&&Number(extra)===q.change;text=q.products.map(p=>`${p.qty} ${p.name} a ${p.price} EUR`).join('; ')+`; pagament ${q.paid} EUR`;expected=`Total ${q.total}; canvi ${q.change}`;submitted=`Total ${answer}; canvi ${extra}`;}
 else if(r.id==='detectius'){if(r.selected===null){feedback(r,'Selecciona primer el pas incorrecte.');render();return;}ok=r.selected===q.bad&&Number(answer)===q.answer;text=q.lines.map((l,i)=>`Pas ${i+1}: ${l}`).join('; ');submitted=`Pas ${r.selected+1}; resultat ${answer}`;expected=`Pas ${q.bad+1}; resultat ${q.answer}`;}
 else {ok=Number(answer)===q.answer;if(r.id==='misteri')text=q.clues.join(' ');if(r.id==='construccio')text=q.text+' Xifres: '+q.digits.join(', ');}
 record(r,text,submitted,expected,ok);if(ok)success(r);else{if(r.id==='construccio'){q.slots.fill(null);r.selected=null;}failedAttempt(r,expected,r.id==='construccio'?'Nombre incorrecte. Les caselles s’han buidat: recomença el repte.':r.id==='mercat'?'Hi ha un error en el total o en el canvi. Revisa la compra.':r.id==='detectius'?'Revisa el pas seleccionat i el resultat final.':'Resposta incorrecta. Revisa el càlcul.');}}
function failedAttempt(r,expected,message){
 if(r.hintShown)r.hintFailures=(r.hintFailures||0)+1;
 if(r.id==='tresor')r.failures[r.index]++;
 const exhausted=r.hintShown?r.hintFailures>=2:r.id==='tresor'&&r.failures[r.index]>=2;
 if(exhausted){r.failedQuestions.push(r.index);r.passed=false;r.pending=true;if(r.id==='tresor')r.outcomes[r.index]='fallat';if(r.id==='bingo')r.failedCells.push(r.questions[r.index].answer);feedback(r,`Resposta errònia. Prova no assolida: has esgotat els dos intents. Solució correcta: ${expected}. Prem el botó següent per continuar.`,'wrong');}
 else feedback(r,message+(r.hintShown?' Et queda un intent després de la pista.':r.id==='tresor'?' Et queda un intent.':''),'wrong');
 render();
}

function placeDomino(key){const r=current();if(!r||r.id!=='domino'||r.done||r.pending)return;let t=r.tiles.find(t=>t.key===key);if(!t||r.chain.some(c=>c.key===key))return;let text=r.chain.length?r.chain.at(-1).operation:r.start,ok=t.left===r.expected;record(r,text,t.left,r.expected,ok);if(ok){r.chain.push(t);r.index++;r.expected=t.next;r.selected=null;r.hintShown=false;r.hintFailures=0;r.done=r.chain.length===6;feedback(r,'Fitxa ben connectada!','ok');render();}else failedAttempt(r,`fitxa que comença per ${r.expected}`,'Aquesta fitxa no coincideix amb el resultat de l’extrem.');}

function placeDigit(slot,index){let r=current(),q=r.questions[r.index];if(r.done||r.pending)return;if(index!==null&&index!==undefined&&!q.slots.includes(index)){q.slots[slot]=index;r.selected=null;}else if(q.slots[slot]!==null){q.slots[slot]=null;}render();}
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b||b.disabled)return;const r=current();
 if(b.dataset.nav){navigate(b.dataset.nav);return;}
 if(b.hasAttribute('data-new')){newGame(state.page);return;}
 if(b.hasAttribute('data-pdf')){await exportPDF(b);return;}
 if(b.hasAttribute('data-next')){r.pending=false;advance(r);return;}
 if(b.hasAttribute('data-hint')){if(!r.hintShown){r.hintShown=true;r.hintFailures=0;if(r.id==='tresor')r.failures[r.index]=0;state.hints[r.id]=(state.hints[r.id]||0)+1;r.touched=true;}render();return;}
 if(b.dataset.cell!==undefined){if(r.pending)return;let n=Number(b.dataset.cell),q=r.questions[r.index],ok=n===q.answer;record(r,q.text,n,q.answer,ok);if(ok){r.marked.push(n);success(r);}else{failedAttempt(r,q.answer,'Aquesta casella no correspon a la pista. Torna-ho a calcular.');}return;}
 if(b.dataset.tile!==undefined){r.selected=Number(b.dataset.tile);render();return;}
 if(b.id==='domino-drop'){if(r.selected===null){feedback(r,'Selecciona una fitxa o arrossega-la aquí.');render();}else placeDomino(r.selected);return;}
 if(b.dataset.digit!==undefined){r.selected=Number(b.dataset.digit);render();return;}
 if(b.dataset.slot!==undefined){placeDigit(Number(b.dataset.slot),r.selected);return;}
 if(b.hasAttribute('data-check-build')){let q=r.questions[r.index];if(q.slots.some(v=>v===null)){feedback(r,'Omple totes les caselles abans de comprovar.');render();return;}let s=q.slots.map(i=>q.digits[i]).join('');if(s[0]==='0'){record(r,q.text+' Xifres: '+q.digits.join(', '),s,q.answer,false);q.slots.fill(null);r.selected=null;failedAttempt(r,q.answer,'Un nombre amb aquestes xifres no pot començar per zero. Les caselles s’han buidat: recomença el repte.');}else tryAnswer(s);return;}
 if(b.dataset.line!==undefined){r.selected=Number(b.dataset.line);render();return;}
});
document.addEventListener('submit',e=>{e.preventDefault();const form=e.target,data=new FormData(form);if(form.id==='name-form'){const name=data.get('name').trim().replace(/\s+/g,' ');if(name.split(' ').length<2){$('#student-name').setCustomValidity('Escriu el nom i els cognoms.');$('#student-name').reportValidity();return;}state.name=name;state.start=new Date();state.clock=Date.now();render();return;}if(form.id==='market-form'){if(numeric(data.get('total'))&&numeric(data.get('change')))tryAnswer(data.get('total'),data.get('change'));}else if(numeric(data.get('answer')))tryAnswer(data.get('answer'));});
document.addEventListener('input',e=>{if(e.target.id==='student-name')e.target.setCustomValidity('');});
document.addEventListener('change',e=>{if(e.target.id==='level')state.level=e.target.value;});
document.addEventListener('dragstart',e=>{let b=e.target.closest('[data-tile],[data-digit]');if(b){e.dataTransfer.setData('text/plain',JSON.stringify({kind:b.dataset.tile!==undefined?'tile':'digit',key:Number(b.dataset.tile??b.dataset.digit)}));e.dataTransfer.effectAllowed='move';}});
document.addEventListener('dragover',e=>{if(e.target.closest('#domino-drop,[data-slot]')){e.preventDefault();e.dataTransfer.dropEffect='move';}});
document.addEventListener('drop',e=>{let b=e.target.closest('#domino-drop,[data-slot]');if(!b)return;e.preventDefault();try{const v=JSON.parse(e.dataTransfer.getData('text/plain'));if(v.kind==='tile'&&b.id==='domino-drop')placeDomino(v.key);if(v.kind==='digit'&&b.dataset.slot!==undefined&&v.key>=0&&v.key<current().questions[current().index].digits.length)placeDigit(Number(b.dataset.slot),v.key);}catch{}});
window.addEventListener('beforeunload',e=>{if(state.name){e.preventDefault();e.returnValue='';}});
$('#finish').onclick=()=>{if(!state.name){navigate('inici');return;}$('#export-status').textContent=state.exported?`Últim PDF descarregat: ${date(new Date(state.exported))}. Descarrega’l de nou si has continuat treballant.`:'Encara no has descarregat cap informe.';$('#end-dialog').showModal();};
$('#continue').onclick=()=>$('#end-dialog').close();$('#dialog-pdf').onclick=()=>exportPDF($('#dialog-pdf'));
$('#reset').onclick=()=>{if(!confirm('S’esborraran el nom, les partides i els resultats. Has descarregat el PDF si el necessites?'))return;$('#end-dialog').close();Object.assign(state,{name:'',start:null,page:'inici',games:{},rounds:[],attempts:[],time:{},hints:{},clock:Date.now(),exported:0});recent.clear();history.replaceState(null,'','#inici');render();};
async function exportPDF(button){tick();const name=state.name;if(!name)return;const original=button.textContent;button.disabled=true;button.textContent='Preparant l’informe…';const snapshot={name,start:state.start,at:new Date(),stats:E.definitions.map(d=>({...d,...statistics(d.id)})),rounds:state.rounds.map(r=>({id:r.id,serial:r.serial,level:r.level,done:r.done,status:roundStatus(r),index:solvedCount(r),outcomes:r.outcomes?.slice()})),total:statistics()};
 try{const {PDFDocument,StandardFonts,rgb}=PDFLib,pdf=await PDFDocument.create(),regular=await pdf.embedFont(StandardFonts.Helvetica),bold=await pdf.embedFont(StandardFonts.HelveticaBold);
 const page=pdf.addPage([595.28,841.89]),ink=rgb(.07,.07,.15),grey=rgb(.4,.43,.5),green=rgb(.15,.6,.36),red=rgb(.82,.22,.21),pale=rgb(.95,.96,.98);
 const clean=s=>String(s).replace(/[’‘]/g,"'").replace(/[“”]/g,'"').replace(/[−–—]/g,'-').replace(/\u202f/g,' ').replace(/\u00a0/g,' ');
 function text(value,x,y,size=10,font=regular,color=ink,width=515){value=clean(value);while(font.widthOfTextAtSize(value,size)>width&&size>6)size-=.25;page.drawText(value,{x,y,size,font,color});}
 function wrap(value,x,y,width=515,size=9,font=regular){let lines=[],row='';for(const word of clean(value).split(/\s+/)){if(font.widthOfTextAtSize(word,size)>width){if(row){lines.push(row);row='';}for(const char of word){if(font.widthOfTextAtSize(row+char,size)>width){lines.push(row);row='';}row+=char;}continue;}const next=row?row+' '+word:word;if(font.widthOfTextAtSize(next,size)>width){lines.push(row);row=word;}else row=next;}if(row)lines.push(row);lines.forEach((line,i)=>text(line,x,y-i*(size+4),size,font,ink,width));return lines.length;}
 function barAt(stats,x,y,width,height=10){const total=stats.ok+stats.bad;page.drawRectangle({x,y,width,height,color:rgb(.85,.86,.89)});if(total){const w=width*stats.ok/total;if(w>0)page.drawRectangle({x,y,width:w,height,color:green});if(w<width)page.drawRectangle({x:x+w,y,width:width-w,height,color:red});}}
 page.drawRectangle({x:0,y:780,width:595.28,height:62,color:ink});text('EL CLUB DELS NOMBRES NATURALS',40,808,19,bold,rgb(1,.89,.4));text('Informe de sessió · Nombres naturals · 1r ESO',40,758,10,regular,grey);
 wrap('Alumne/a: '+snapshot.name,40,740,515,13,bold);text('Inici: '+date(snapshot.start),40,705,9);text('Informe generat: '+date(snapshot.at),40,690,9);
 const total=snapshot.total,attempts=total.ok+total.bad,percent=attempts?Math.round(total.ok/attempts*100)+'% d’encerts':'Sense respostes';
 text('Resum de la sessió',40,660,14,bold);barAt(total,40,638,515,14);text(`${total.ok} encerts · ${total.bad} errades · ${percent}`,40,622,10,bold);
 text(`${total.completed} partides superades · ${total.notPassed} no superades · ${total.corrected} correccions · ${total.hints} pistes`,40,605,9);
 text('Temps actiu en activitats: '+duration(total.time),40,590,9);
 page.drawRectangle({x:40,y:547,width:515,height:25,color:ink});text('Activitat',47,555,9,bold,rgb(1,1,1),100);text('Encerts / errades',165,555,9,bold,rgb(1,1,1),130);text('Partides S / NS',314,555,8.5,bold,rgb(1,1,1),100);text('Pistes',427,555,8.5,bold,rgb(1,1,1),40);text('Temps',477,555,8.5,bold,rgb(1,1,1),72);
 snapshot.stats.forEach((stats,i)=>{const top=547-i*43,bottom=top-43;if(i%2===0)page.drawRectangle({x:40,y:bottom,width:515,height:43,color:pale});const count=stats.ok+stats.bad;
 text(stats.name,47,top-17,10,bold,ink,110);const levels=[...new Set(snapshot.rounds.filter(r=>r.id===stats.id).map(r=>r.level==='inicial'?'I':r.level==='mitja'?'M':'R'))];text(levels.length?'Nivells: '+levels.join(', '):'No iniciada',47,top-33,7.5,regular,grey,110);
 text(`${stats.ok} / ${stats.bad}${count?' ('+Math.round(stats.ok/count*100)+'%)':''}`,165,top-15,9,regular,ink,126);barAt(stats,165,top-33,122,8);
 text(`${stats.completed} / ${stats.notPassed}`,314,top-16,10,bold,ink,96);text('Correccions: '+stats.corrected,314,top-32,7.5,regular,grey,100);text(stats.hints,435,top-20,9,regular,ink,33);text(duration(stats.time),477,top-20,8.5,regular,ink,75);
 page.drawLine({start:{x:40,y:bottom},end:{x:555,y:bottom},thickness:.5,color:rgb(.8,.82,.86)});
 });
 text('Verd: encerts. Vermell: errades. S: superades. NS: no superades.',40,186,8.5,bold);text('NS inclou partides en curs, deixades a mitges i acabades amb proves no assolides.',40,172,8.5);text('Nivells: I = inicial, M = mitjà, R = repte.',40,158,8.5);
 const island=snapshot.rounds.filter(r=>r.id==='tresor').at(-1);if(island){const labels=['Platja','Palmera','Pont','Cova','Volcà','Cofre'];wrap('Última expedició: '+island.outcomes.map((outcome,i)=>labels[i]+': '+(outcome==='assolit'?'assolit':outcome==='fallat'?'no assolit':'pendent')).join('; '),40,140,515,8.5);}
 wrap('Cada comprovació enviada és un intent. Els encerts després d’un error també compten i s’indiquen com a correccions. Després de la pista hi ha dos intents. Si s’esgoten, es mostra la solució i la prova queda no assolida.',40,98,515,8.5);
 text('Missió Orió és una web independent i els seus resultats no s’inclouen.',40,65,8.5);text('El detall dels intents es pot consultar a «El meu progrés» mentre la sessió continua oberta.',40,51,8.5);
 text('JJB Avatares con IA · Informe de la sessió',40,26,8,regular,grey);text('1 / 1',525,26,8,regular,grey,30);
 pdf.setTitle('Informe de sessió - El Club dels Nombres Naturals');pdf.setAuthor('El Club dels Nombres Naturals');const bytes=await pdf.save(),blob=new Blob([bytes],{type:'application/pdf'}),url=URL.createObjectURL(blob),a=document.createElement('a');const safe=name.normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9_-]/g,'_').slice(0,60);a.href=url;a.download=`informe_naturals_${safe}_${new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Madrid'}).format(snapshot.at)}.pdf`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);state.exported=Date.now();$('#export-status').textContent='Informe descarregat. El pots adjuntar al correu o penjar a Classroom.';
 }catch(error){console.error(error);alert('No s’ha pogut generar el PDF. Mantén la pàgina oberta i torna-ho a intentar.');}finally{button.disabled=false;button.textContent=original;}}
window.addEventListener('hashchange',()=>{let id=location.hash.slice(1);if(id==='inici'||id==='progres'||def(id))navigate(id);});
render();

// Reintenta una imatge si una petició local ha quedat interrompuda.
document.addEventListener('error', event => {
  const image = event.target;
  if (!(image instanceof HTMLImageElement) || image.dataset.loadRetry) return;
  image.dataset.loadRetry = '1';
  const url = new URL(image.src, document.baseURI);
  url.searchParams.set('retry', String(Date.now()));
  setTimeout(() => { if (image.isConnected) image.src = url.href; }, 200);
}, true);
